# Generated by Django 5.0.1 on 2024-01-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 15, 3, 48, 122270)),
        ),
        migrations.AddField(
            model_name='task',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 15, 3, 48, 122270)),
        ),
    ]
